### ISSUE TITLE
Attempted to call require with invalid argument(s).

### ISSUE THREAD

**Issue by ToastEngine** [Gskartwii/Rbx_CustomFont#2]
Having an issue doing the following, Roboto works but the one I added (Deutsch Gothic) doesn't seem too.

**The font atlas the tool generated**
`https://pastebin.com/8fhpYTeS`

**INPUT**
`Font.Replace("Deutsch Gothic", MainMenu.Title.TextLabel)`

**OUTPUT**
`
15:21:17.267 - Stack Begin
15:21:17.267 - Script 'ReplicatedFirst.ExternalDependencies.Font', Line 500 - field new
15:21:17.267 - Script 'ReplicatedFirst.ExternalDependencies.Font', Line 662 - field Replace
15:21:17.268 - Script 'ReplicatedFirst.InsomnisFramework.Modules.client_menu', Line 35 - method OpenMenu
15:21:17.268 - Script 'ReplicatedFirst.InsomnisFramework.Modules.client_interface', Line 76 - method init
15:21:17.268 - Script 'ReplicatedFirst.InsomnisFramework.client_bootstrap', Line 25
15:21:17.268 - Stack End
`
Any help would be appreciated!

**Comment by Gskartwii** [comment]
I'll try to get back to you as soon as possible. It's been a while since I last looked at this project. Could you post the full error that is printed? The issue currently only contains the stack trace.

**Comment by ToastEngine** [comment]
Solved it by redoing the atlas generator a couple times no idea how but it suddenly worked when I added more fonts then went back to gothic
