### ISSUE TITLE
generation tool borked

### ISSUE THREAD

**Issue by checkraisefold** [Gskartwii/Rbx_CustomFont#4]
[image](https://i.vgy.me/qWgvFi.png)
excuse me sir, but where did the middle part of my 3 go

[PxPlus_IBM_EGA8.zip](https://github.com/Gskartwii/Rbx_CustomFont/files/4808996/PxPlus_IBM_EGA8.zip)
repro:
use this font in the gen tool
size 14, haven't tested on other sizes, though any image size is fine
zoom in
muh 3,,, wgere did them iddle of it go noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by Gskartwii** [comment]
Unfortunately, I'm no longer maintaining this project. I've now updated the README to reflect this. Please check #5.

**Comment by ghost** [comment]
(necropost) borke haha funny overused joke

**Comment by checkraisefold** [comment]
> (necropost) borke haha funny overused joke

the bigger joke is every repository on your account
